SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN ITEM_TREE AS T 
ON T.ITEM_ID=I.ITEM_ID
JOIN ITEM_INFO AS INFO 
ON INFO.ITEM_ID=T.PARENT_ITEM_ID
WHERE INFO.RARITY ="RARE"
ORDER BY ITEM_ID DESC